sudo: false

dist: xenial
language: node_js
node_js:
  - "stable"
  - "lts/*"

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - node_modules

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt-get install wine4.0.1

before_script:
  - "npm install -g electron --unsafe-perm=true"
  - "npm install electron-packager -g"
  - "yarn"

script:
  - yarn package-win
  - yarn create-installer-win