sudo: true

dist: xenial
language: node_js

node_js:
  - "stable"
  - "lts/*"

branches:
  only:
    - master

cache:
  directories:
  - node_modules

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt install --install-recommends winehq-stable

before_script:
  - "sudo npm install -g electron --unsafe-perm=true"
  - "sudo npm install electron-packager -g"
  - "yarn"

script:
  - yarn package-win
  - yarn create-installer-win