sudo: true

dist: xenial
language: node_js

node_js:
  - "stable"
  - "lts/*"

mono:
  - latest

branches:
  only:
    - master

cache:
  directories:
  - node_modules

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt install --install-recommends winehq-stable

before_script:
  - "npm install -g electron --unsafe-perm=true"
  - "npm install electron-packager -g"
  - "yarn"

script:
  - yarn package-win
  - yarn create-installer-win