dist: xenial

language: node_js

node_js:
  - "stable"
  - "lts/*"

branches:
  only:
    - master

cache:
  directories:
  - node_modules

before_script:
  - "npm install -g electron --unsafe-perm=true"
  - "yarn"

script:
  - electron main.js